wizz/models.py
from itsdangerous import TimedJSONWebSignatureSerializer as serializer
from datetime import datetime
from wizz import db
from flask import current_app



class Document(db.Model):
    __tablename__ = 'documents'
    {'extend_existing': True}
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64))
    image_file = db.Column(db.String(300), nullable=False, default='image.jpg')
    saved_image_file = db.Column(db.String(300), nullable=False, default='image1.jpg')
    timestamp = db.Column(db.DateTime(), default=datetime.utcnow)

    def generate_token(self, expiration=3600):
        s = serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'reset': self.id}).decode('utf-8')

class NewDocument(db.Model):
    __tablename__ = 'newdocuments'
    {'extend_existing': True}
    id = db.Column(db.Integer, primary_key=True)
    image_file = db.Column(db.String(300))

wizz/main/forms.py
from flask import request
from flask_wtf import FlaskForm
from wtforms.fields import SubmitField
from flask_wtf.file import FileAllowed, FileField


class UploadForm(FlaskForm):
    profile_picture = FileField('Upload picture', validators=[
        FileAllowed(['jpg', 'png', 'pdf'])])

    submit = SubmitField('Submit')

wizz/__init__.py
from flask import Flask
from flask_mail import Mail
from flask_sqlalchemy import SQLAlchemy
from config import config
import os
basedir = os.path.abspath(os.path.dirname(__file__))


db = SQLAlchemy()
mail = Mail()


def create_app(config_name):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    db.init_app(app)
    mail.init_app(app)

    from wizz.main import main

    app.register_blueprint(main)

    
    return app

wizz/app.py
import os
from flask_migrate import Migrate
from wizz import create_app, db


# app = create_app(os.getenv('FLASK_CONFIG') or 'default')
app = create_app("production")
migrate = Migrate(app, db)

wizz/main/__init__.py
from flask import Blueprint


main = Blueprint('main', __name__)

from . import routes

wizz/main/routes.py
import os
import secrets
import convertapi
from PIL import Image
from . import main
from ..models import Document, NewDocument
from wizz import db
from flask import json, render_template, redirect, request, current_app, url_for, abort, send_from_directory, flash, jsonify
from werkzeug.utils import secure_filename


@main.route('/dashboard', methods=['GET', 'POST'])
def dashboard():
    return render_template("Dashboard.html")

@main.route('/select-document/<pdf>', methods=['GET', 'POST'])
def selectDocument(pdf):
    document = NewDocument.query.filter_by(image_file=pdf).first()
    link = "http://polywizz.herokuapp.com/client_create/" + document.image_file
    # link = "http://localhost:5000/client_create/" + document.image_file
    print(link)
    return render_template("select-document.html", link=link, pdf=document.image_file, document=document)

@main.route('/process-history', methods=['GET', 'POST'])
def processHistory():
    return render_template("process-history.html")

@main.route('/all-history', methods=['GET', 'POST'])
def allHistory():
    return render_template("all-history.html")

@main.route('/create/<image>', methods=['GET', 'POST'])
def create(image):
    imagePdf = Document.query.filter_by(image_file=image).first()
    return render_template("create.html", imagePdf=imagePdf.image_file)

@main.route('/client_create/<image>', methods=['GET', 'POST'])
def clientCreate(image):
    imagePdf = NewDocument.query.filter_by(image_file=image).first()

    return render_template("create.html", imagePdf=imagePdf.image_file)


@main.route('/', methods=['GET', 'POST'])
def getFile():
    if request.method == "POST":
        print("request.files", request.files["file"])
        uploaded_file = request.files["file"]
        filename = secure_filename(uploaded_file.filename)
        if filename != '':
            file_ext = os.path.splitext(filename)[1]
            if file_ext not in current_app.config['UPLOAD_EXTENSIONS']:
                print("Abort 400")
                abort(400)
            if file_ext != ".pdf" and file_ext in current_app.config["WORD_EXTENSIONS"]:
                picture_file = save_picture(uploaded_file)
                picture_path = os.path.join(
                                current_app.root_path, 'static/images', picture_file)

                convertapi.api_secret = '01FK85WQktz8GYZz'
                result = convertapi.convert('pdf', { 'File': picture_path })

                pdf_file_name = picture_file.split(".")[0]
                pdf_file_with_ext = pdf_file_name + ".pdf"

                new_picture_path = os.path.join(
                                current_app.root_path, 'static/images', pdf_file_with_ext)
                # save to file
                result.file.save(new_picture_path)
                document = Document(image_file=pdf_file_with_ext, name="Adegoke Bright")
                db.session.add(document)
                db.session.commit()
                print("File uploaded successfully...............")
                flash('Your file has been successfully uploaded!', 'success')
                return redirect(url_for("main.create", image=pdf_file_with_ext))

            elif file_ext != ".pdf" and file_ext in current_app.config["PICTURE_EXTENSIONS"]:
                picture_file = save_picture(uploaded_file)
                picture_path = os.path.join(
                                current_app.root_path, 'static/images', picture_file)
                image1 = Image.open(picture_path)
                im1 = image1.convert('RGB')
                pdf_file_name = picture_file.split(".")[0]
                pdf_file_with_ext = pdf_file_name + ".pdf"
                new_picture_path = os.path.join(
                                current_app.root_path, 'static/images', pdf_file_with_ext)
                im1.save(new_picture_path)
                print(pdf_file_with_ext)
                document = Document(image_file=pdf_file_with_ext, name="Adegoke Bright")
                db.session.add(document)
                db.session.commit()
                print("File uploaded successfully...............")
                flash('Your file has been successfully uploaded!', 'success')
                return redirect(url_for("main.create", image=pdf_file_with_ext))
            else:
                picture_file = save_picture(uploaded_file)
                document = Document(image_file=picture_file, name="Adegoke Bright")
                db.session.add(document)
                db.session.commit()
                print("File uploaded successfully...............")
                flash('Your file has been successfully uploaded!', 'success')
                return redirect(url_for("main.create", image=picture_file))
    
    return render_template("add-new.html")


@main.route('/save/<filename>', methods=['GET', 'POST'])
def download(filename):
    document = Document.query.filter_by(image_file=filename).first()
    document.saved_image_file = document.image_file
    db.session.commit()
    print("File saved successfully...............")
    return redirect(request.referrer)


@main.route('/upload_for_client', methods=['GET', 'POST'])
def uploadForClient():
    if request.method == "POST":
        uploaded_file = request.files["file"]
        print(uploaded_file)
        filename = secure_filename(uploaded_file.filename)
        if filename != '':
            file_ext = os.path.splitext(filename)[1]
            if file_ext not in current_app.config['AGENT_UPLOAD_EXTENSIONS']:
                print("Abort 400")
                abort(400)
            picture_file = save_picture(uploaded_file)
            document = NewDocument(image_file=picture_file)
            db.session.add(document)
            db.session.commit()
            flash('Your file has been successfully uploaded!', 'success')
            # return redirect(url_for("main.clientCreate", image=picture_file))
            return redirect(url_for("main.selectDocument", pdf=picture_file))
    
    
    return render_template("fill.html")

# @main.route('/client_response/<image>', methods=['GET', 'POST'])
# def clientResponse(image):
#     print(image)
    
#     return render_template("create.html", imagePdf=imagePdf.image_file)


def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(
            current_app.root_path, 'static/images', picture_fn)
    form_picture.save(picture_path)

    return picture_fn


# href="mailto:brightaverix@gmail.com?subject=HI&body={{link}}"

wizz/templates/add-new.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>PolyWizz</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="../static/plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="../static/css/adminlte.min.css">
  <!-- summernote -->
  <link rel="stylesheet" href="../static/plugins/summernote/summernote-bs4.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

  <style>
    .note-editor.note-frame .note-editing-area {
    min-height: 350px;
}
.opacity{
  opacity:0;
  position: absolute;
  top:0;
  height:400px;
  width: 100%;
  cursor: pointer;
}
.opacity-div{
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  position: relative;
}
.pad{
  height: 400px;
  width:400px;
  margin: auto;
}
.bigicon{
  font-size: 60px;
  background-color: transparent;
 margin-bottom: 0.2em;
 color:#007bff;
}
.file-upload{
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  animation: imganim 1s infinite linear both;
  margin-top: 4em;
  text-align: center;
  position: relative;
  z-index: 1;
width:300px;

}
.file-upload a{
  background-color: transparent;
  border:1px solid #007bff;
  color:#007bff;
}

@keyframes imganim {
from {height: 50px;}
to {height: 55px;} 
}
.success{
  font-size: 20px;
  color:#fff;
  background-color: #007bff;
  border-radius: 50%;
  padding:1rem;
  margin-bottom: 10px;
}


  </style>
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">
   <!-- Navbar -->
   <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"
          ><i class="fas fa-bars"></i
        ></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="./Dashboard.html" class="nav-link">Home</a>
      </li>
      
    </ul>

    <!-- SEARCH FORM -->
    

   
   
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
        

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex ml-2">
        <div class="info">
          <strong><a href="#" class="d-block">Firstname Lastname</a></strong>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul
          class="nav nav-pills nav-sidebar flex-column"
          data-widget="treeview"
          role="menu"
          data-accordion="false"
        >
        

          <li class="nav-item pt-3">
            <a href="{{ url_for('main.getFile') }}" class="nav-link">
              <i class="fa fa-plus nav-icon"></i>
              <p>Add New Document</p>
            </a>
          </li>

          <li class="nav-item pt-3">
            <a href="{{ url_for('main.uploadForClient') }}" class="nav-link">
              <i class="fa fa-plus nav-icon"></i>
              <p>Upload Created Doc(Agent)</p>
            </a>
          </li>
          <!-- <li class="nav-item pt-3">
            <a href="create.html" class="nav-link">
              <i class="fa fa-file nav-icon"></i>
              <p>Create New PDF Form</p>
            </a>
          </li> -->


          <li class="nav-item has-treeview pt-3">
            <a href="#" class="nav-link">
              <i class="nav-icon fa fa-history"></i>
              <p>
                History
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{ url_for('main.processHistory') }}" class="nav-link">
                  <i class="fa fa-tasks nav-icon"></i>
                  <p>In Process</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ url_for('main.allHistory') }}" class="nav-link">
                  <i class="fa fa-history nav-icon"></i>
                  <p>All History</p>
                </a>
              </li>

             
            </ul>
          </li>

          <li class="nav-item pt-3">
            <a href="logout.html" class="nav-link">
              <i class="fa fa-power-off nav-icon"></i>
              <p>Logout</p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>


  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Upload New File</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Add New Document</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="card card-outline card-info">
            <div class="card-header">
              <h3 class="card-title">
                Add New Document
               
              </h3>
              <!-- tools box -->
            
              <!-- /. tools -->
            </div>
            <!-- /.card-header -->
            <form action="" method="POST" enctype="multipart/form-data">
              <div class="card-body pad">
                <div class="mb-3 opacity-div">
                  <i class="fas fa-file bigicon"></i>
                  <p class='text-center'>Drag 'n' drop a file here,
                    <br>or <strong> <span style="color:#007bff;" >Browse files</span></strong></p>
  
                    <input
                    class="form-control form-control-navbar opacity"
                    type="file"
                    id="input"
                    name="file"
                    placeholder="Search"
                    aria-label="Search"
                  />
                  <div class="file-upload" id="file-upload-filename">
                   
                  </div>
                </div>
               
  
               
              </div>
            </form>
            
           
          </div>
        </div>
        <!-- /.col-->
      </div>
      <!-- ./row -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="../static/js/jquery-3.3.1.min.js"></script>
<!-- Bootstrap 4 -->
<script src="../static/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="../static/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="../static/js/demo.js"></script>
<!-- Summernote -->
<script src="../static/plugins/summernote/summernote-bs4.min.js"></script>
<script>
  $(function () {
    // Summernote
    $('.textarea').summernote()
  })

  const inputEl=document.getElementById('input');
 const infoArea = document.getElementById( 'file-upload-filename' );
 
  inputEl.addEventListener("change", function(event) {
    const input = event.srcElement;
    const fileName = input.files[0].name;
    infoArea.innerHTML = `<i class="fa fa-check success"></i>   ${fileName} <input type="submit" class ="btn b-0 rounded-0 mt-2" value="Continue" />`;
});

</script>
</body>
</html>

wizz/templates/all-history.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Polywizz</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="../static/plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- DataTables -->
  <link rel="stylesheet" href="../static/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="../static/css/adminlte.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">
   <!-- Navbar -->
   <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"
          ><i class="fas fa-bars"></i
        ></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="./Dashboard.html" class="nav-link">Home</a>
      </li>
      
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input
          class="form-control form-control-navbar"
          type="search"
          placeholder="Search"
          aria-label="Search"
        />
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

   
   
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex ml-2">
        <div class="info">
          <strong><a href="#" class="d-block">Firstname Lastname</a></strong>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul
          class="nav nav-pills nav-sidebar flex-column"
          data-widget="treeview"
          role="menu"
          data-accordion="false"
        >
          <!-- Add icons to the links using the .nav-icon class
           with font-awesome or any other icon font library -->

         

          <li class="nav-item pt-3">
            <a href="{{ url_for('main.getFile') }}" class="nav-link">
              <i class="fa fa-plus nav-icon"></i>
              <p>Add New Document</p>
            </a>
          </li>

          <li class="nav-item pt-3">
            <a href="{{ url_for('main.uploadForClient') }}" class="nav-link">
              <i class="fa fa-plus nav-icon"></i>
              <p>Upload Created Doc(Agent)</p>
            </a>
          </li>
        
          <li class="nav-item has-treeview pt-3">
            <a href="#" class="nav-link">
              <i class="nav-icon fa fa-history"></i>
              <p>
                History
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{ url_for('main.processHistory') }}" class="nav-link">
                  <i class="fa fa-tasks nav-icon"></i>
                  <p>In Process</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ url_for('main.allHistory') }}" class="nav-link">
                  <i class="fa fa-history nav-icon"></i>
                  <p>All History</p>
                </a>
              </li>

             
            </ul>
          </li>

          <li class="nav-item pt-3">
            <a href="logout.html" class="nav-link">
              <i class="fa fa-power-off nav-icon"></i>
              <p>Logout</p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>


  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>All History</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">All History</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-12">
              <div class="card">
                <div class="card-header">
                  <h3 class="card-title">View all History</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                  <table id="example1" class="table table-bordered table-hover">
                    <thead>
                      <tr>
                        <th>S/N</th>
                        <th>Document's Name</th>
                        <th>Date Uploaded</th>
                        <th>View</th>
                        <th>Delete File</th>
                        <th>Status</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>1</td>
                        <td>Document one</td>
                        <td>26/05/2022</td>
                        <td>
                          <a href=""><i class="fa fa-eye"></i></a>
                        </td>
                        <td>
                          <a href="http://"><i class="fa fa-trash"></i></a>
                        </td>
                        <td>
                          <p>Completed</p>
                        </td>
                      </tr>
                      <tr>
                        <td>2</td>
                        <td>Document Two</td>
                        <td>26/05/2022</td>
                        <td>
                          <a href=""><i class="fa fa-eye"></i></a>
                        </td>
                        <td>
                          <a href="http://"><i class="fa fa-trash"></i></a>
                        </td>
                        <td>
                         <p>Incompelte</p>
                        </td>
                      </tr>
                      <tr>
                         <td>3</td>
                        <td>Document Three</td>
                        <td>26/05/2022</td>
                        <td>
                          <a href=""><i class="fa fa-eye"></i></a>
                        </td>
                        <td>
                          <a href="http://"><i class="fa fa-trash"></i></a>
                        </td>
                        <td>
                         <p>Completed</p>
                        </td>
                      </tr>
                      <tr>
                       <td>4</td>
                        <td>Document Four</td>
                        <td>26/05/2022</td>
                        <td>
                          <a href=""><i class="fa fa-eye"></i></a>
                        </td>
                        <td>
                          <a href="http://"><i class="fa fa-trash"></i></a>
                        </td>
                        <td>
                          <p>Completed</p>
                        </td>
                      </tr>
                      <tr>
                         <td>5</td>
                        <td>Document Five</td>
                        <td>26/05/2022</td>
                        <td>
                          <a href=""><i class="fa fa-eye"></i></a>
                        </td>
                        <td>
                          <a href="http://"><i class="fa fa-trash"></i></a>
                        </td>
                        <td>
                          <p>Incomplete</p>
                        </td>
                      </tr>

                      <tr>
                        <td>6</td>
                        <td>Document Six</td>
                        <td>26/05/2022</td>
                        <td>
                          <a href=""><i class="fa fa-eye"></i></a>
                        </td>
                        <td>
                          <a href="http://"><i class="fa fa-trash"></i></a>
                        </td>
                        <td>
                         <p>Incomplete</p>
                        </td>
                      </tr>
                      <tr>
                         <td>7</td>
                        <td>Document Seven</td>
                        <td>26/05/2024</td>
                        <td>
                          <a href=""><i class="fa fa-eye"></i></a>
                        </td>
                        <td>
                          <a href="http://"><i class="fa fa-trash"></i></a>
                        </td>
                        <td>
                         <p>Completed</p>
                        </td>
                      </tr>
                      <tr>
                        <td>8</td>
                        <td>Document Eight</td>
                        <td>22/05/2022</td>
                        <td>
                          <a href=""><i class="fa fa-eye"></i></a>
                        </td>
                        <td>
                          <a href="http://"><i class="fa fa-trash"></i></a>
                        </td>
                        <td>
                         <p>Sent </p>
                        </td>
                      </tr>
                      <tr>
                        <td>9</td>
                        <td>Document Nine</td>
                        <td>26/09/2025</td>
                        <td>
                          <a href=""><i class="fa fa-eye"></i></a>
                        </td>
                        <td>
                          <a href="http://"><i class="fa fa-trash"></i></a>
                        </td>
                        <td>
                         <p>Sent</p>
                        </td>
                      </tr>
                      <tr>
                        <td>10</td>
                        <td>Document Ten</td>
                        <td>27/03/2022</td>
                        <td>
                          <a href=""><i class="fa fa-eye"></i></a>
                        </td>
                        <td>
                          <a href="http://"><i class="fa fa-trash"></i></a>
                        </td>
                        <td>
                          <p>Completed</p>
                        </td>
                      </tr>
                    </tbody>
                    <tfoot>
                      <tr>
                        <th>S/N</th>
                        <th>Document's Name</th>
                        <th>Date Uploaded</th>
                        <th>View</th>
                        <th>Delete File</th>
                        <th>Status</th>
                      </tr>
                    </tfoot>
                  </table>
                </div>
                <!-- /.card-body -->
              </div>
              <!-- /.card -->
            </div>
            <!-- /.col -->
          </div>
          <!-- /.row -->
        </section>
        <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 3.0.0-rc.3
    </div>
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights
    reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="../static/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="../static/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- DataTables -->
<script src="../static/plugins/datatables/jquery.dataTables.js"></script>
<script src="../static/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
<!-- AdminLTE App -->
<script src="../static/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="../static/js/demo.js"></script>
<!-- page script -->
<script>
  $(function () {
    $("#example1").DataTable();
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
    });
  });
</script>
</body>
</html>

wizz/templates/plugins/jsgrid/demos/index.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>jsGrid - Simple jQuery DataGrid - Demos</title>
    <link rel="stylesheet" type="text/css" href="demos.css" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,600,400' rel='stylesheet' type='text/css'>
</head>
<body>
    <div class="navigation">
        <h1>jsGrid Demos</h1>
        <ul>
            <li><a href="basic.html" target="demo">Basic Scenario</a></li>
            <li><a href="static-data.html" target="demo">Static Data</a></li>
            <li><a href="odata-service.html" target="demo">OData Service</a></li>
            <li><a href="data-manipulation.html" target="demo">Data Manipulation</a></li>
            <li><a href="validation.html" target="demo">Validation</a></li>
            <li><a href="sorting.html" target="demo">Sorting</a></li>
            <li><a href="loading-by-page.html" target="demo">Loading by Page</a></li>
            <li><a href="custom-view.html" target="demo">Custom View</a></li>
            <li><a href="custom-row-renderer.html" target="demo">Custom Row Renderer</a></li>
            <li><a href="external-pager.html" target="demo">External Pager</a></li>
            <li><a href="custom-grid-field.html" target="demo">Custom Grid Field</a></li>
            <li><a href="localization.html" target="demo">Localization</a></li>
        </ul>
    </div>
    <div class="demo-frame">
        <iframe name="demo" src="basic.html"></iframe>
    </div>
</body>
</html>